PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dct: <http://purl.org/dc/terms/>
SELECT ?term ?synonym ?definition ?source ?spec
WHERE {
  ?concept a skos:Concept;
  skos:prefLabel ?term;  
  skos:definition ?definition;
  OPTIONAL {?concept skos:altLabel ?synonym}
  OPTIONAL {?concept dct:source ?source}
  OPTIONAL {?concept dct:isPartOf ?spec}
} ORDER BY (?term)